// Builds a simple "Howell Luau — Site Plan" Excalidraw scene and prints base64.
let s = 1000; const sd = () => (s += 7); const vn = () => Math.floor(Math.random() * 2147483647);
const shape = (type, x, y, w, h, bg, stroke) => ({ id: `sh-${sd()}`, type, x, y, width: w, height: h, angle: 0, strokeColor: stroke, backgroundColor: bg, fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid', roughness: 1, opacity: 100, groupIds: [], frameId: null, roundness: type === 'rectangle' ? { type: 3 } : null, seed: sd(), version: 1, versionNonce: vn(), isDeleted: false, boundElements: [], updated: 1, link: null, locked: false });
const label = (c, text, x, y, w) => { const id = `${c.id}-t`; c.boundElements = [{ id, type: 'text' }]; return { id, type: 'text', x, y, width: w, height: 25, angle: 0, strokeColor: '#1e1e1e', backgroundColor: 'transparent', fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid', roughness: 1, opacity: 100, groupIds: [], frameId: null, roundness: null, seed: sd(), version: 1, versionNonce: vn(), isDeleted: false, boundElements: [], updated: 1, link: null, locked: false, fontSize: 16, fontFamily: 1, text, textAlign: 'center', verticalAlign: 'middle', containerId: c.id, originalText: text, lineHeight: 1.25, baseline: 18 }; };
const title = (text, x, y) => ({ id: `ttl-${sd()}`, type: 'text', x, y, width: 460, height: 40, angle: 0, strokeColor: '#1e1e1e', backgroundColor: 'transparent', fillStyle: 'solid', strokeWidth: 2, strokeStyle: 'solid', roughness: 1, opacity: 100, groupIds: [], frameId: null, roundness: null, seed: sd(), version: 1, versionNonce: vn(), isDeleted: false, boundElements: [], updated: 1, link: null, locked: false, fontSize: 28, fontFamily: 1, text, textAlign: 'left', verticalAlign: 'top', containerId: null, originalText: text, lineHeight: 1.25, baseline: 24 });
const els = [title('Howell Luau — Site Plan', 60, 40)];
for (const [name, x] of [['Guest Hut', 80], ['Howell Hut', 230], ['Staff Hut', 380]]) { const r = shape('rectangle', x, 120, 110, 110, '#ffec99', '#846358'); els.push(r, label(r, name, x, 162, 110)); }
const luau = shape('rectangle', 110, 300, 250, 170, '#ffd8a8', '#e8590c'); els.push(luau, label(luau, 'Luau', 110, 378, 250));
const coco = shape('ellipse', 420, 300, 170, 170, '#a5d8ff', '#1971c2'); els.push(coco, label(coco, 'Coconut Bobbing', 420, 378, 170));
const scene = { elements: els, appState: { viewBackgroundColor: '#ffffff', gridSize: null }, files: {} };
process.stdout.write(Buffer.from(JSON.stringify(scene), 'utf-8').toString('base64'));
