-- 0153_permissions_seed_actions_delta_002.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 28 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read) VALUES
    ('bam.agent_audit.get', 'bam', 'agent_audit', 'get', 'bam agent_audit get', false, false, true),
    ('bam.agent_policy_check.create', 'bam', 'agent_policy_check', 'create', 'bam agent_policy_check create', false, false, false),
    ('bam.audit_log.list', 'bam', 'audit_log', 'list', 'bam audit_log list', false, false, true),
    ('bam.auth_oauth_callback.create', 'bam', 'auth_oauth_callback', 'create', 'bam auth_oauth_callback create', false, false, false),
    ('bam.auth_oauth_link.create', 'bam', 'auth_oauth_link', 'create', 'bam auth_oauth_link create', false, false, false),
    ('bam.me_notification.list', 'bam', 'me_notification', 'list', 'bam me_notification list', false, false, true),
    ('bam.me_time_entry.list', 'bam', 'me_time_entry', 'list', 'bam me_time_entry list', false, false, true),
    ('bam.org_member_activity.get', 'bam', 'org_member_activity', 'get', 'bam org_member_activity get', false, false, true),
    ('bam.organization.list', 'bam', 'organization', 'list', 'bam organization list', false, false, true),
    ('bam.project_activity.get', 'bam', 'project_activity', 'get', 'bam project_activity get', false, false, true),
    ('bam.project_report_burndown.get', 'bam', 'project_report_burndown', 'get', 'bam project_report_burndown get', false, false, true),
    ('bam.project_report_cfd.get', 'bam', 'project_report_cfd', 'get', 'bam project_report_cfd get', false, false, true),
    ('bam.project_report_time_tracking.get', 'bam', 'project_report_time_tracking', 'get', 'bam project_report_time_tracking get', false, false, true),
    ('bam.project_report_velocity.get', 'bam', 'project_report_velocity', 'get', 'bam project_report_velocity get', false, false, true),
    ('bam.project_task.get', 'bam', 'project_task', 'get', 'bam project_task get', false, false, true),
    ('bam.proposal_decide.create', 'bam', 'proposal_decide', 'create', 'bam proposal_decide create', false, false, false),
    ('bam.proposal.list', 'bam', 'proposal', 'list', 'bam proposal list', false, false, true),
    ('bam.superuser_permission_divergence.list', 'bam', 'superuser_permission_divergence', 'list', 'bam superuser_permission_divergence list', false, false, true),
    ('bam.task_comment.get', 'bam', 'task_comment', 'get', 'bam task_comment get', false, false, true),
    ('bam.user_active.update', 'bam', 'user_active', 'update', 'bam user_active update', false, false, false),
    ('bam.user_email.update', 'bam', 'user_email', 'update', 'bam user_email update', false, false, false),
    ('bam.user_login_history.get', 'bam', 'user_login_history', 'get', 'bam user_login_history get', false, false, true),
    ('bam.user_membership.create', 'bam', 'user_membership', 'create', 'bam user_membership create', false, false, false),
    ('bam.user_membership.update', 'bam', 'user_membership', 'update', 'bam user_membership update', false, false, false),
    ('bam.user_project.get', 'bam', 'user_project', 'get', 'bam user_project get', false, false, true),
    ('bam.user_set_default_org.create', 'bam', 'user_set_default_org', 'create', 'bam user_set_default_org create', false, false, false),
    ('bam.user.list', 'bam', 'user', 'list', 'bam user list', false, false, true),
    ('bond.company_deal.get', 'bond', 'company_deal', 'get', 'bond company_deal get', false, false, true)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read;
