-- 0155_permissions_seed_actions_delta_003.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 1 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bam.file.list', 'bam', 'file', 'list', 'bam file list', false, false, true, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;

-- 36 retired permission(s)
DELETE FROM permissions WHERE id IN (
    'bam.agent.heartbeat',
    'bam.auth_bootstrap.create',
    'bam.auth_change_password.create',
    'bam.auth_login.create',
    'bam.auth_logout.create',
    'bam.auth_me.list',
    'bam.auth_me.update',
    'bam.auth_oauth_authorize.get',
    'bam.auth_oauth_callback.create',
    'bam.auth_oauth_link.create',
    'bam.auth_oauth_provider.list',
    'bam.auth_org.list',
    'bam.auth_register.create',
    'bam.auth_switch_org.create',
    'bam.auth_verify_email.create',
    'bam.chat.create',
    'bam.file_*.list',
    'bam.guest_accept.create',
    'bam.me_calendar.list',
    'bam.project_calendar.get',
    'bam.public_beta_signup.create',
    'bam.public_config.list',
    'bam.queue.list',
    'bam.root_redirect.list',
    'bam.task.reopen',
    'bam.task_move_to_terminal_phase.create',
    'bam.webhook_github.create',
    'bam.webhook_slack_command.create',
    'book.calendar_ical.create',
    'book.calendar_ical.get',
    'helpdesk.auth_login.create',
    'helpdesk.auth_logout.create',
    'helpdesk.auth_me.list',
    'helpdesk.auth_register.create',
    'helpdesk.auth_verify_email.create',
    'helpdesk.public_config.list'
);
