-- 0160_permissions_seed_actions_delta_004.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 13 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bam.superuser_permission_catalog.list', 'bam', 'superuser_permission_catalog', 'list', 'bam superuser_permission_catalog list', false, false, true, true),
    ('bam.superuser_permission_group.list', 'bam', 'superuser_permission_group', 'list', 'bam superuser_permission_group list', false, false, true, true),
    ('bam.superuser_permission_group.create', 'bam', 'superuser_permission_group', 'create', 'bam superuser_permission_group create', false, false, false, true),
    ('bam.superuser_permission_group.get', 'bam', 'superuser_permission_group', 'get', 'bam superuser_permission_group get', false, false, true, true),
    ('bam.superuser_permission_group.update', 'bam', 'superuser_permission_group', 'update', 'bam superuser_permission_group update', false, false, false, true),
    ('bam.superuser_permission_group.delete', 'bam', 'superuser_permission_group', 'delete', 'bam superuser_permission_group delete', true, false, false, true),
    ('bam.superuser_permission_group.set_defaults', 'bam', 'superuser_permission_group', 'set_defaults', 'bam superuser_permission_group set_defaults', false, false, false, true),
    ('bam.superuser_permission_group.reset', 'bam', 'superuser_permission_group', 'reset', 'bam superuser_permission_group reset', false, false, false, true),
    ('bam.superuser_permission_user.get', 'bam', 'superuser_permission_user', 'get', 'bam superuser_permission_user get', false, false, true, true),
    ('bam.superuser_permission_user.set_membership', 'bam', 'superuser_permission_user', 'set_membership', 'bam superuser_permission_user set_membership', false, false, false, true),
    ('bam.superuser_permission_user.set_override', 'bam', 'superuser_permission_user', 'set_override', 'bam superuser_permission_user set_override', false, false, false, true),
    ('bam.superuser_permission_user.clear_override', 'bam', 'superuser_permission_user', 'clear_override', 'bam superuser_permission_user clear_override', true, false, false, true),
    ('bam.superuser_permission_user.reattach', 'bam', 'superuser_permission_user', 'reattach', 'bam superuser_permission_user reattach', true, false, false, true)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
