-- 0162_permissions_seed_actions_delta_005.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 3 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bam.superuser_deploy_settings.get', 'bam', 'superuser_deploy_settings', 'get', 'bam superuser_deploy_settings get', false, false, true, true),
    ('bam.superuser_deploy_settings.update', 'bam', 'superuser_deploy_settings', 'update', 'bam superuser_deploy_settings update', false, false, false, true),
    ('bam.superuser_deploy_settings.verify', 'bam', 'superuser_deploy_settings', 'verify', 'bam superuser_deploy_settings verify', false, false, false, true)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
