-- 0206_permissions_seed_actions_delta_011.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 14 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bin.asset_download.get', 'bin', 'asset_download', 'get', 'bin asset_download get', false, false, true, false),
    ('bin.asset_version.create', 'bin', 'asset_version', 'create', 'bin asset_version create', false, false, false, false),
    ('bin.asset_version.get', 'bin', 'asset_version', 'get', 'bin asset_version get', false, false, true, false),
    ('bin.asset.archive', 'bin', 'asset', 'archive', 'bin asset archive', true, true, false, false),
    ('bin.asset.create', 'bin', 'asset', 'create', 'bin asset create', false, false, false, false),
    ('bin.asset.get', 'bin', 'asset', 'get', 'bin asset get', false, false, true, false),
    ('bin.asset.list', 'bin', 'asset', 'list', 'bin asset list', false, false, true, false),
    ('bin.folder.create', 'bin', 'folder', 'create', 'bin folder create', false, false, false, false),
    ('bin.folder.delete', 'bin', 'folder', 'delete', 'bin folder delete', true, true, false, false),
    ('bin.folder.get', 'bin', 'folder', 'get', 'bin folder get', false, false, true, false),
    ('bin.folder.list', 'bin', 'folder', 'list', 'bin folder list', false, false, true, false),
    ('bin.folder.update', 'bin', 'folder', 'update', 'bin folder update', false, false, false, false),
    ('bin.version_complete.create', 'bin', 'version_complete', 'create', 'bin version_complete create', false, false, false, false),
    ('bin.version.get', 'bin', 'version', 'get', 'bin version get', false, false, true, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
