-- 0208_permissions_seed_actions_delta_012.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 9 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bin.asset_raw.get', 'bin', 'asset_raw', 'get', 'bin asset_raw get', false, false, true, false),
    ('bin.asset_upload.create', 'bin', 'asset_upload', 'create', 'bin asset_upload create', false, false, false, false),
    ('bin.data_comment_resolve.create', 'bin', 'data_comment_resolve', 'create', 'bin data_comment_resolve create', false, false, false, false),
    ('bin.data_comment.create', 'bin', 'data_comment', 'create', 'bin data_comment create', false, false, false, false),
    ('bin.data_comment.get', 'bin', 'data_comment', 'get', 'bin data_comment get', false, false, true, false),
    ('bin.data_row.create', 'bin', 'data_row', 'create', 'bin data_row create', false, false, false, false),
    ('bin.data_row.update', 'bin', 'data_row', 'update', 'bin data_row update', false, false, false, false),
    ('bin.data_session.create', 'bin', 'data_session', 'create', 'bin data_session create', false, false, false, false),
    ('bin.data.get', 'bin', 'data', 'get', 'bin data get', false, false, true, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
