-- 0211_permissions_seed_actions_delta_014.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 12 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bay.annotation_resolve.create', 'bay', 'annotation_resolve', 'create', 'bay annotation_resolve create', false, false, false, false),
    ('bay.asset_version.create', 'bay', 'asset_version', 'create', 'bay asset_version create', false, false, false, false),
    ('bay.asset_version.get', 'bay', 'asset_version', 'get', 'bay asset_version get', false, false, true, false),
    ('bay.asset.archive', 'bay', 'asset', 'archive', 'bay asset archive', true, true, false, false),
    ('bay.asset.create', 'bay', 'asset', 'create', 'bay asset create', false, false, false, false),
    ('bay.asset.get', 'bay', 'asset', 'get', 'bay asset get', false, false, true, false),
    ('bay.asset.list', 'bay', 'asset', 'list', 'bay asset list', false, false, true, false),
    ('bay.version_annotation.create', 'bay', 'version_annotation', 'create', 'bay version_annotation create', false, false, false, false),
    ('bay.version_annotation.get', 'bay', 'version_annotation', 'get', 'bay version_annotation get', false, false, true, false),
    ('bay.version_decision.get', 'bay', 'version_decision', 'get', 'bay version_decision get', false, false, true, false),
    ('bay.version_decision.update', 'bay', 'version_decision', 'update', 'bay version_decision update', false, false, false, false),
    ('bay.version.get', 'bay', 'version', 'get', 'bay version get', false, false, true, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
