-- 0222_permissions_seed_actions_delta_018.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 30 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('blip.app.create', 'blip', 'app', 'create', 'blip app create', false, false, false, false),
    ('blip.app.delete', 'blip', 'app', 'delete', 'blip app delete', true, true, false, false),
    ('blip.app.read', 'blip', 'app', 'read', 'blip app read', false, false, true, false),
    ('blip.app.update', 'blip', 'app', 'update', 'blip app update', false, false, false, false),
    ('blip.collection.toggle', 'blip', 'collection', 'toggle', 'blip collection toggle', false, false, false, false),
    ('blip.entry.export', 'blip', 'entry', 'export', 'blip entry export', false, false, true, false),
    ('blip.entry.purge', 'blip', 'entry', 'purge', 'blip entry purge', true, true, false, false),
    ('blip.entry.read', 'blip', 'entry', 'read', 'blip entry read', false, false, true, false),
    ('blip.field.index', 'blip', 'field', 'index', 'blip field index', false, false, false, false),
    ('blip.field.metric', 'blip', 'field', 'metric', 'blip field metric', false, false, false, false),
    ('blip.key.create', 'blip', 'key', 'create', 'blip key create', false, false, false, false),
    ('blip.key.list', 'blip', 'key', 'list', 'blip key list', false, false, true, false),
    ('blip.key.revoke', 'blip', 'key', 'revoke', 'blip key revoke', false, false, false, false),
    ('blip.key.suspend', 'blip', 'key', 'suspend', 'blip key suspend', false, false, false, false),
    ('blip.key.update', 'blip', 'key', 'update', 'blip key update', false, false, false, false),
    ('blip.ratelimit.manage', 'blip', 'ratelimit', 'manage', 'blip ratelimit manage', false, false, false, false),
    ('blip.retention.manage', 'blip', 'retention', 'manage', 'blip retention manage', false, false, false, false),
    ('blip.timelapse.create', 'blip', 'timelapse', 'create', 'blip timelapse create', false, false, false, false),
    ('blip.timelapse.read', 'blip', 'timelapse', 'read', 'blip timelapse read', false, false, true, false),
    ('blip.transform.manage', 'blip', 'transform', 'manage', 'blip transform manage', false, false, false, false),
    ('blip.view.create', 'blip', 'view', 'create', 'blip view create', false, false, false, false),
    ('blip.view.delete', 'blip', 'view', 'delete', 'blip view delete', true, true, false, false),
    ('blip.view.read', 'blip', 'view', 'read', 'blip view read', false, false, true, false),
    ('blip.view.update', 'blip', 'view', 'update', 'blip view update', false, false, false, false),
    ('blip.watch.create', 'blip', 'watch', 'create', 'blip watch create', false, false, false, false),
    ('blip.watch.delete', 'blip', 'watch', 'delete', 'blip watch delete', true, true, false, false),
    ('blip.watch.enable', 'blip', 'watch', 'enable', 'blip watch enable', false, false, false, false),
    ('blip.watch.read', 'blip', 'watch', 'read', 'blip watch read', false, false, true, false),
    ('blip.watch.test', 'blip', 'watch', 'test', 'blip watch test', false, false, false, false),
    ('blip.watch.update', 'blip', 'watch', 'update', 'blip watch update', false, false, false, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
