-- 0229_permissions_seed_actions_delta_020.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 9 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('basis.datasource.read', 'basis', 'datasource', 'read', 'basis datasource read', false, false, true, false),
    ('basis.explain.run', 'basis', 'explain', 'run', 'basis explain run', false, false, true, false),
    ('basis.metric.certify', 'basis', 'metric', 'certify', 'basis metric certify', false, true, false, false),
    ('basis.metric.decertify', 'basis', 'metric', 'decertify', 'basis metric decertify', false, true, false, false),
    ('basis.metric.define', 'basis', 'metric', 'define', 'basis metric define', false, false, false, false),
    ('basis.metric.deprecate', 'basis', 'metric', 'deprecate', 'basis metric deprecate', true, true, false, false),
    ('basis.metric.read', 'basis', 'metric', 'read', 'basis metric read', false, false, true, false),
    ('basis.metric.update', 'basis', 'metric', 'update', 'basis metric update', false, false, false, false),
    ('basis.metric.version', 'basis', 'metric', 'version', 'basis metric version', false, false, false, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;

-- NOTE: the generator also flagged 3 pre-existing retired perms
-- (bam.config_health*) as removable. That is drift that predates the Basis work
-- and is intentionally NOT bundled into this basis-scoped delta; it is tracked
-- separately so an unrelated cleanup does not ride along with a feature migration.
