-- 0232_permissions_seed_actions_delta_021.sql
-- Why: Catalog delta for the Braid app. Seeds the 9 braid.* permission rows
--   (spec 3.4). Generated by scripts/build-permission-delta.mjs; the generator's
--   proposed removal of bam.config_health* rows was stripped - those rows are a
--   local-dev-DB artifact of a different branch, not owned by this delta.
-- Client impact: additive only. INSERT...ON CONFLICT is idempotent.

-- 9 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('braid.candidate.read', 'braid', 'candidate', 'read', 'braid candidate read', false, false, true, false),
    ('braid.profile.merge', 'braid', 'profile', 'merge', 'braid profile merge', true, true, false, false),
    ('braid.profile.read', 'braid', 'profile', 'read', 'braid profile read', false, false, true, false),
    ('braid.profile.resolve', 'braid', 'profile', 'resolve', 'braid profile resolve', false, false, false, false),
    ('braid.profile.split', 'braid', 'profile', 'split', 'braid profile split', true, true, false, false),
    ('braid.rule.read', 'braid', 'rule', 'read', 'braid rule read', false, false, true, false),
    ('braid.rule.write', 'braid', 'rule', 'write', 'braid rule write', false, false, false, false),
    ('braid.settings.read', 'braid', 'settings', 'read', 'braid settings read', false, false, true, false),
    ('braid.settings.write', 'braid', 'settings', 'write', 'braid settings write', false, false, false, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
