-- 0237_permissions_seed_actions_delta_022.sql
-- Why: Catalog delta for the Bulwark app. Seeds the 12 bulwark.* permission
--   rows (spec Section 10 lines 679-692). bulwark-api routes call
--   requireCan('bulwark.<resource>.<verb>') but no catalog rows existed, so
--   under the per-action resolver every non-SuperUser hit implicit_deny.
--   Generated by scripts/build-permission-delta.mjs; hand-authored flags in
--   scripts/generate-permission-manifest.mjs. Only contract.delete is
--   manifest-destructive (is_destructive + requires_confirmation).
-- Client impact: additive only. INSERT...ON CONFLICT is idempotent.

-- 12 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bulwark.compliance.chase', 'bulwark', 'compliance', 'chase', 'bulwark compliance chase', false, false, false, false),
    ('bulwark.compliance.read', 'bulwark', 'compliance', 'read', 'bulwark compliance read', false, false, true, false),
    ('bulwark.contract.delete', 'bulwark', 'contract', 'delete', 'bulwark contract delete', true, true, false, false),
    ('bulwark.contract.read', 'bulwark', 'contract', 'read', 'bulwark contract read', false, false, true, false),
    ('bulwark.contract.write', 'bulwark', 'contract', 'write', 'bulwark contract write', false, false, false, false),
    ('bulwark.deadline.read', 'bulwark', 'deadline', 'read', 'bulwark deadline read', false, false, true, false),
    ('bulwark.deadline.write', 'bulwark', 'deadline', 'write', 'bulwark deadline write', false, false, false, false),
    ('bulwark.notice.draft', 'bulwark', 'notice', 'draft', 'bulwark notice draft', false, false, false, false),
    ('bulwark.obligation.read', 'bulwark', 'obligation', 'read', 'bulwark obligation read', false, false, true, false),
    ('bulwark.obligation.write', 'bulwark', 'obligation', 'write', 'bulwark obligation write', false, false, false, false),
    ('bulwark.settings.read', 'bulwark', 'settings', 'read', 'bulwark settings read', false, false, true, false),
    ('bulwark.settings.write', 'bulwark', 'settings', 'write', 'bulwark settings write', false, false, false, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
