-- 0242_permissions_seed_actions_delta_023.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 22 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('burn.attribution.read', 'burn', 'attribution', 'read', 'burn attribution read', false, false, true, false),
    ('burn.attribution.write', 'burn', 'attribution', 'write', 'burn attribution write', false, false, false, false),
    ('burn.changeorder.draft', 'burn', 'changeorder', 'draft', 'burn changeorder draft', false, false, false, false),
    ('burn.costrate.read', 'burn', 'costrate', 'read', 'burn costrate read', false, false, true, false),
    ('burn.costrate.write', 'burn', 'costrate', 'write', 'burn costrate write', false, false, false, false),
    ('burn.deliverable.read', 'burn', 'deliverable', 'read', 'burn deliverable read', false, false, true, false),
    ('burn.deliverable.write', 'burn', 'deliverable', 'write', 'burn deliverable write', false, false, false, false),
    ('burn.engagement.delete', 'burn', 'engagement', 'delete', 'burn engagement delete', true, true, false, false),
    ('burn.engagement.read', 'burn', 'engagement', 'read', 'burn engagement read', false, false, true, false),
    ('burn.engagement.write', 'burn', 'engagement', 'write', 'burn engagement write', false, false, false, false),
    ('burn.envelope.confirm', 'burn', 'envelope', 'confirm', 'burn envelope confirm', false, false, false, false),
    ('burn.financials.read', 'burn', 'financials', 'read', 'burn financials read', false, false, true, false),
    ('burn.financials.read_all', 'burn', 'financials', 'read_all', 'burn financials read_all', false, false, true, false),
    ('burn.precheck.mark_wrong', 'burn', 'precheck', 'mark_wrong', 'burn precheck mark_wrong', false, false, false, false),
    ('burn.precheck.override', 'burn', 'precheck', 'override', 'burn precheck override', false, false, false, false),
    ('burn.precheck.read', 'burn', 'precheck', 'read', 'burn precheck read', false, false, true, false),
    ('burn.precheck.run', 'burn', 'precheck', 'run', 'burn precheck run', false, false, false, false),
    ('burn.rule.write', 'burn', 'rule', 'write', 'burn rule write', false, false, false, false),
    ('burn.settings.read', 'burn', 'settings', 'read', 'burn settings read', false, false, true, false),
    ('burn.settings.write', 'burn', 'settings', 'write', 'burn settings write', false, false, false, false),
    ('burn.variance.read', 'burn', 'variance', 'read', 'burn variance read', false, false, true, false),
    ('burn.variance.write', 'burn', 'variance', 'write', 'burn variance write', false, false, false, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
