-- 0251_bursar_rls.sql
-- Why: Row-level-security foundation for every bursar_* table. Policies are GENERATED by a
--   DO $$ loop over information_schema for the bursar_ prefix (PG16 has no CREATE POLICY IF
--   NOT EXISTS, so each is DROP POLICY IF EXISTS then CREATE POLICY, per 0116_rls_foundation
--   .sql). bursar_scope_library takes the variant policy that also admits global rows
--   (organization_id IS NULL AND is_global) and a WITH CHECK forbidding org-null inserts, so
--   the built-in library does not vanish the day a non-superuser role is armed. test/
--   rls-coverage.test.ts asserts every bursar_% table is covered.
-- Client impact: additive only. Policies are created but the connecting role is currently a
--   superuser and bypasses RLS unconditionally, so behavior is unchanged until the platform
--   arms a NOSUPERUSER / NOBYPASSRLS application role. The explicit organization_id predicate
--   in every query remains the only tenant boundary until then (spec 6.3).

DO $$
DECLARE
    tbl text;
    pol text;
BEGIN
    FOR tbl IN
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
          AND table_name LIKE 'bursar\_%' ESCAPE '\'
          AND table_type = 'BASE TABLE'
        ORDER BY table_name
    LOOP
        -- Enable RLS on the table (idempotent - ENABLE is a no-op if already enabled).
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);

        pol := tbl || '_org_isolation';
        EXECUTE format('DROP POLICY IF EXISTS %I ON %I', pol, tbl);

        IF tbl = 'bursar_scope_library' THEN
            -- Variant policy (spec 6.1): the blanket predicate evaluates NULL (not true) for
            -- a global row, so global built-ins would disappear under a bound org GUC. Admit
            -- them explicitly, and forbid org callers from writing org-null (global) rows via
            -- WITH CHECK. The BEFORE INSERT OR UPDATE OR DELETE trigger in 0247 is the second
            -- half of the same guard.
            EXECUTE format(
                'CREATE POLICY %I ON %I FOR ALL '
                || 'USING (organization_id = current_setting(''app.current_org_id'', true)::uuid '
                || 'OR (organization_id IS NULL AND is_global)) '
                || 'WITH CHECK (organization_id = current_setting(''app.current_org_id'', true)::uuid)',
                pol, tbl);
        ELSE
            EXECUTE format(
                'CREATE POLICY %I ON %I FOR ALL '
                || 'USING (organization_id = current_setting(''app.current_org_id'', true)::uuid)',
                pol, tbl);
        END IF;
    END LOOP;
END $$;
