-- 0258_permissions_seed_actions_delta_024.sql
-- Why: Catalog delta. Adds permissions that landed since the previous
--   seed (snapshot 0145 + any prior deltas) and removes any rows that
--   were retired. Generated by scripts/build-permission-delta.mjs.
-- Client impact: additive (new rows) + minor cleanup (removals).
--   Re-running is safe; INSERT...ON CONFLICT and DELETE both idempotent.

-- 36 new permission(s)
INSERT INTO permissions (id, app, resource, verb, description, is_destructive, requires_confirmation, is_read, requires_superuser) VALUES
    ('bursar.award.amend', 'bursar', 'award', 'amend', 'bursar award amend', true, true, false, false),
    ('bursar.award.create', 'bursar', 'award', 'create', 'bursar award create', false, true, false, false),
    ('bursar.award.read', 'bursar', 'award', 'read', 'bursar award read', false, false, true, false),
    ('bursar.award.terminate', 'bursar', 'award', 'terminate', 'bursar award terminate', true, true, false, false),
    ('bursar.baseline.read', 'bursar', 'baseline', 'read', 'bursar baseline read', false, false, true, false),
    ('bursar.coverage.override', 'bursar', 'coverage', 'override', 'bursar coverage override', false, false, false, false),
    ('bursar.coverage.read', 'bursar', 'coverage', 'read', 'bursar coverage read', false, false, true, false),
    ('bursar.detector.mark_wrong', 'bursar', 'detector', 'mark_wrong', 'bursar detector mark_wrong', false, false, false, false),
    ('bursar.draft.approve', 'bursar', 'draft', 'approve', 'bursar draft approve', false, false, false, false),
    ('bursar.draft.create', 'bursar', 'draft', 'create', 'bursar draft create', false, false, false, false),
    ('bursar.draft.read', 'bursar', 'draft', 'read', 'bursar draft read', false, false, true, false),
    ('bursar.gate.run', 'bursar', 'gate', 'run', 'bursar gate run', false, false, false, false),
    ('bursar.leveling.run', 'bursar', 'leveling', 'run', 'bursar leveling run', false, false, false, false),
    ('bursar.library.write', 'bursar', 'library', 'write', 'bursar library write', false, false, false, false),
    ('bursar.mismatch.dismiss', 'bursar', 'mismatch', 'dismiss', 'bursar mismatch dismiss', true, false, false, false),
    ('bursar.mismatch.read', 'bursar', 'mismatch', 'read', 'bursar mismatch read', false, false, true, false),
    ('bursar.mismatch.resolve', 'bursar', 'mismatch', 'resolve', 'bursar mismatch resolve', false, false, false, false),
    ('bursar.offer.ingest', 'bursar', 'offer', 'ingest', 'bursar offer ingest', false, false, false, false),
    ('bursar.offer.read', 'bursar', 'offer', 'read', 'bursar offer read', false, false, true, false),
    ('bursar.offer.unseal', 'bursar', 'offer', 'unseal', 'bursar offer unseal', false, true, false, false),
    ('bursar.offer.write', 'bursar', 'offer', 'write', 'bursar offer write', false, false, false, false),
    ('bursar.renewal.decide', 'bursar', 'renewal', 'decide', 'bursar renewal decide', false, false, false, false),
    ('bursar.renewal.read', 'bursar', 'renewal', 'read', 'bursar renewal read', false, false, true, false),
    ('bursar.request.read', 'bursar', 'request', 'read', 'bursar request read', false, false, true, false),
    ('bursar.request.write', 'bursar', 'request', 'write', 'bursar request write', false, false, false, false),
    ('bursar.scope.confirm', 'bursar', 'scope', 'confirm', 'bursar scope confirm', false, false, false, false),
    ('bursar.scope.promote_rival', 'bursar', 'scope', 'promote_rival', 'bursar scope promote_rival', false, true, false, false),
    ('bursar.scope.write', 'bursar', 'scope', 'write', 'bursar scope write', true, false, false, false),
    ('bursar.settings.read', 'bursar', 'settings', 'read', 'bursar settings read', false, false, true, false),
    ('bursar.settings.write', 'bursar', 'settings', 'write', 'bursar settings write', false, false, false, false),
    ('bursar.spend.import', 'bursar', 'spend', 'import', 'bursar spend import', false, false, false, false),
    ('bursar.spend.read', 'bursar', 'spend', 'read', 'bursar spend read', false, false, true, false),
    ('bursar.spend.read_all', 'bursar', 'spend', 'read_all', 'bursar spend read_all', false, false, true, false),
    ('bursar.vendor.delete', 'bursar', 'vendor', 'delete', 'bursar vendor delete', true, true, false, false),
    ('bursar.vendor.read', 'bursar', 'vendor', 'read', 'bursar vendor read', false, false, true, false),
    ('bursar.vendor.write', 'bursar', 'vendor', 'write', 'bursar vendor write', false, false, false, false)
ON CONFLICT (id) DO UPDATE SET
    app = EXCLUDED.app,
    resource = EXCLUDED.resource,
    verb = EXCLUDED.verb,
    description = EXCLUDED.description,
    is_destructive = EXCLUDED.is_destructive,
    requires_confirmation = EXCLUDED.requires_confirmation,
    is_read = EXCLUDED.is_read,
    requires_superuser = EXCLUDED.requires_superuser;
