import { describe, it, expect, beforeAll, afterAll } from 'vitest';
import postgres from 'postgres';

/**
 * RLS coverage probe (spec 6.1 / 6.3).
 *
 * The RLS policies on every bursar_* table are GENERATED by a DO $$ loop over
 * information_schema in migration 0251, rather than enumerated by hand. That is the safe
 * shape - a new bursar_* table is covered automatically - but it means the guarantee "every
 * bursar_* table has an org-isolation policy" is only ever as good as the loop actually
 * running against the live schema. This test asserts exactly that against a migrated DB:
 * every base table whose name matches bursar\_% has a row-security policy, RLS is enabled on
 * it, and bursar_scope_library carries the VARIANT policy (a WITH CHECK) rather than the
 * blanket one.
 *
 * CI provides a migrated Postgres and DATABASE_URL. Locally, point DATABASE_URL at the
 * compose stack. When it is absent the suite SKIPS LOUDLY rather than silently passing.
 */

const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
  console.warn(
    '[bursar-api/rls-coverage] SKIPPING: DATABASE_URL is not set, so per-table RLS policy ' +
      'coverage cannot be verified. Point DATABASE_URL at a migrated database (the compose ' +
      'stack or a CI service container) to exercise it.',
  );
}

describe.skipIf(!DATABASE_URL)('bursar_* RLS policy coverage', () => {
  let sql: postgres.Sql;

  beforeAll(() => {
    sql = postgres(DATABASE_URL as string, { max: 2, onnotice: () => {} });
  });

  afterAll(async () => {
    if (sql) await sql.end({ timeout: 5 });
  });

  it('every bursar_% base table has RLS enabled and exactly one org-isolation policy', async () => {
    const tables = await sql<Array<{ tablename: string; rowsecurity: boolean; policy_count: number }>>`
      SELECT t.tablename,
             t.rowsecurity,
             (SELECT count(*)::int FROM pg_policies p WHERE p.schemaname = 'public' AND p.tablename = t.tablename) AS policy_count
      FROM pg_tables t
      WHERE t.schemaname = 'public'
        AND t.tablename LIKE 'bursar\\_%'
      ORDER BY t.tablename`;

    // There must be tables at all - a zero-row result would silently pass.
    expect(tables.length).toBeGreaterThan(0);

    const missingRls = tables.filter((t) => !t.rowsecurity).map((t) => t.tablename);
    expect(missingRls, `bursar_* tables with RLS disabled: ${missingRls.join(', ')}`).toEqual([]);

    const uncovered = tables.filter((t) => t.policy_count < 1).map((t) => t.tablename);
    expect(uncovered, `bursar_* tables with no RLS policy: ${uncovered.join(', ')}`).toEqual([]);
  });

  it('bursar_scope_library carries the variant policy (admits globals, forbids org-null inserts)', async () => {
    const rows = await sql<Array<{ policyname: string; qual: string | null; with_check: string | null }>>`
      SELECT policyname, qual, with_check
      FROM pg_policies
      WHERE schemaname = 'public' AND tablename = 'bursar_scope_library'`;

    expect(rows.length).toBe(1);
    const pol = rows[0];
    // USING admits global rows.
    expect(pol.qual).toContain('is_global');
    // WITH CHECK forbids an org caller from writing an org-null (global) row.
    expect(pol.with_check).not.toBeNull();
    expect(pol.with_check).toContain('current_org_id');
  });
});
