/**
 * Word list for passphrase password generation. Curated for:
 *  - All 3–6 character lowercase ASCII (no diacritics, no apostrophes)
 *  - No words that sound the same as common others (no homophones that
 *    a typing user would routinely confuse: "their" / "there" / "they're")
 *  - No words with offensive or trademarked sense
 *  - Easy to spell from speech (admin reads it to a user over the phone)
 *
 * Entropy: 1024 words = exactly 10 bits per word, so a 4-word passphrase
 * has ~40 bits of word entropy (plus the small bonus from digits/symbol
 * when enabled). A 6-word passphrase reaches ~60 bits — comparable to a
 * 10-char alphanumeric password from our 56-char alphabet.
 *
 * This is intentionally a generic ~English word set; if the platform
 * grows i18n needs the list can be swapped for a language-specific one
 * keyed off the org or user locale without changing the generator
 * contract.
 */

export const PASSPHRASE_WORDS: readonly string[] = [
  'able', 'about', 'above', 'acid', 'acorn', 'acre', 'actor', 'add', 'admit', 'adopt',
  'adult', 'aged', 'agent', 'ahead', 'aim', 'air', 'ajar', 'alarm', 'album', 'alert',
  'alike', 'alive', 'alley', 'allow', 'alloy', 'aloe', 'aloud', 'alpha', 'also', 'amber',
  'amid', 'ample', 'angel', 'anger', 'angle', 'angry', 'ankle', 'apple', 'apply', 'apron',
  'arch', 'arena', 'argue', 'arm', 'armor', 'army', 'arrow', 'art', 'ash', 'aside',
  'ask', 'aspen', 'asset', 'atlas', 'atom', 'attic', 'audio', 'auger', 'aunt', 'avid',
  'await', 'awake', 'aware', 'awning', 'axis', 'axle', 'baby', 'back', 'badge', 'bake',
  'balm', 'banjo', 'bank', 'barn', 'base', 'basil', 'bath', 'bay', 'beach', 'bead',
  'beak', 'beam', 'bean', 'bear', 'beast', 'beat', 'bee', 'beech', 'beef', 'bell',
  'belt', 'bench', 'bend', 'bento', 'beret', 'berry', 'best', 'bevel', 'bike', 'bin',
  'birch', 'bird', 'birth', 'bison', 'black', 'blade', 'blast', 'blaze', 'bleak', 'blend',
  'bless', 'blimp', 'blink', 'block', 'bloom', 'blot', 'blue', 'bluff', 'blunt', 'blur',
  'boa', 'board', 'boat', 'body', 'bog', 'boil', 'bold', 'bolt', 'bond', 'bone',
  'bongo', 'bonus', 'book', 'boost', 'boot', 'booth', 'borax', 'born', 'boron', 'bossy',
  'bowl', 'box', 'boy', 'brace', 'braid', 'brain', 'brake', 'brand', 'brass', 'brave',
  'bravo', 'bread', 'break', 'breed', 'brew', 'brick', 'bride', 'brief', 'brim', 'bring',
  'brisk', 'broad', 'broil', 'broke', 'brook', 'broom', 'broth', 'brow', 'brown', 'brunt',
  'brush', 'bud', 'buff', 'buggy', 'build', 'built', 'bulk', 'bull', 'bump', 'bunch',
  'bunk', 'bunny', 'burst', 'bus', 'bush', 'busy', 'butte', 'buy', 'buzz', 'byte',
  'cab', 'cable', 'cache', 'cacti', 'cadet', 'cafe', 'cage', 'cake', 'calf', 'calm',
  'camel', 'camp', 'can', 'canal', 'candy', 'cane', 'canon', 'canoe', 'cap', 'cape',
  'card', 'care', 'cargo', 'carp', 'cart', 'carve', 'case', 'cash', 'cast', 'cause',
  'cave', 'cedar', 'cello', 'cent', 'chain', 'chair', 'chalk', 'champ', 'chant', 'chap',
  'char', 'chart', 'chase', 'cheap', 'check', 'cheer', 'chef', 'chess', 'chest', 'chew',
  'chick', 'chief', 'child', 'chili', 'chime', 'chin', 'chip', 'chirp', 'chop', 'chord',
  'chose', 'chub', 'chunk', 'churn', 'cider', 'cigar', 'cinch', 'cite', 'city', 'civic',
  'clam', 'clamp', 'clan', 'clap', 'clash', 'clasp', 'class', 'clay', 'clean', 'clear',
  'cleat', 'clef', 'clerk', 'click', 'cliff', 'climb', 'cling', 'clink', 'clip', 'cloak',
  'clock', 'clog', 'close', 'cloth', 'cloud', 'clove', 'clown', 'club', 'cluck', 'clue',
  'clump', 'coach', 'coast', 'coat', 'cobra', 'cocoa', 'coil', 'coin', 'cold', 'comb',
  'come', 'comet', 'comic', 'cone', 'cope', 'copy', 'coral', 'cord', 'cork', 'corn',
  'cot', 'couch', 'cough', 'count', 'court', 'cove', 'cover', 'cow', 'crab', 'craft',
  'cramp', 'crane', 'crank', 'crash', 'crate', 'crave', 'crawl', 'crazy', 'cream', 'crepe',
  'crest', 'crew', 'crib', 'crime', 'crimp', 'crisp', 'croak', 'crock', 'crook', 'cross',
  'crow', 'crowd', 'crown', 'crude', 'cruel', 'crumb', 'crush', 'crust', 'cry', 'crypt',
  'cub', 'cube', 'cuff', 'cup', 'curb', 'curd', 'cure', 'curl', 'curly', 'curry',
  'curve', 'cute', 'cycle', 'daily', 'dairy', 'dance', 'dandy', 'darts', 'dash', 'data',
  'date', 'daze', 'dean', 'dear', 'debit', 'debt', 'deck', 'decoy', 'deed', 'deep',
  'deer', 'delay', 'dell', 'delta', 'demo', 'den', 'denim', 'dense', 'depot', 'depth',
  'derby', 'desk', 'detox', 'dew', 'diary', 'dice', 'digit', 'dill', 'dime', 'diner',
  'ding', 'dingo', 'disco', 'dish', 'disk', 'ditch', 'dive', 'doc', 'dock', 'dodge',
  'doe', 'dog', 'doily', 'doing', 'doll', 'dome', 'donor', 'door', 'dose', 'dot',
  'dove', 'down', 'dowry', 'doze', 'draft', 'drag', 'drama', 'drank', 'draw', 'dread',
  'dream', 'dress', 'drew', 'drift', 'drill', 'drink', 'drip', 'drive', 'droid', 'drone',
  'drool', 'drop', 'drove', 'drown', 'drum', 'dry', 'duck', 'duct', 'due', 'duet',
  'duke', 'dull', 'duly', 'dump', 'dune', 'dunk', 'duo', 'dusk', 'dust', 'duty',
  'each', 'eagle', 'eager', 'early', 'earn', 'earth', 'easel', 'east', 'easy', 'eaten',
  'echo', 'edge', 'edict', 'edify', 'edit', 'eel', 'effort', 'egg', 'eight', 'elbow',
  'elder', 'elf', 'elite', 'elk', 'elm', 'elope', 'elude', 'elves', 'email', 'embed',
  'ember', 'empty', 'enact', 'end', 'enemy', 'enjoy', 'enter', 'entry', 'envoy', 'equal',
  'equip', 'erase', 'error', 'erupt', 'essay', 'etch', 'ether', 'event', 'every', 'evict',
  'evoke', 'exact', 'exit', 'extra', 'eye', 'fable', 'face', 'fact', 'fade', 'fail',
  'faint', 'fair', 'falcon', 'fall', 'false', 'fame', 'fancy', 'fang', 'farm', 'fast',
  'fat', 'fault', 'fawn', 'feast', 'feat', 'fed', 'fee', 'feed', 'feel', 'felt',
  'femur', 'fence', 'fend', 'fern', 'ferry', 'fetch', 'feud', 'fever', 'fiber', 'fib',
  'fife', 'fig', 'fight', 'film', 'final', 'find', 'fine', 'finch', 'fire', 'firm',
  'fish', 'fist', 'five', 'fix', 'fizz', 'flag', 'flail', 'flair', 'flake', 'flame',
  'flap', 'flash', 'flask', 'flat', 'flaw', 'flax', 'flea', 'fleck', 'fled', 'flee',
  'fleet', 'flesh', 'flew', 'flex', 'flick', 'flier', 'fling', 'flint', 'flip', 'flirt',
  'flock', 'flood', 'floor', 'flop', 'flora', 'floss', 'flour', 'flow', 'flu', 'fluff',
  'fluid', 'flung', 'flush', 'flute', 'flux', 'fly', 'foal', 'foam', 'fog', 'foil',
  'fold', 'folk', 'fond', 'food', 'fool', 'foot', 'force', 'fork', 'form', 'fort',
  'forty', 'forum', 'fossil', 'foul', 'found', 'four', 'fowl', 'fox', 'frail', 'frame',
  'free', 'fresh', 'fret', 'frill', 'frisk', 'frog', 'from', 'front', 'frost', 'froth',
  'frown', 'froze', 'fruit', 'fudge', 'fuel', 'full', 'fume', 'fund', 'fungi', 'funny',
  'fur', 'furry', 'fuse', 'gag', 'gain', 'gala', 'game', 'gap', 'gape', 'gas',
  'gash', 'gate', 'gather', 'gauge', 'gaunt', 'gave', 'gawky', 'gay', 'gaze', 'gear',
  'gecko', 'gel', 'gem', 'genie', 'gent', 'germ', 'getup', 'ghost', 'giant', 'gift',
  'gig', 'gild', 'gill', 'gilt', 'gimpy', 'ginger', 'give', 'glad', 'glare', 'glass',
  'gleam', 'glee', 'glide', 'glint', 'globe', 'gloom', 'glory', 'gloss', 'glove', 'glow',
  'glue', 'glum', 'gnaw', 'goal', 'goat', 'godly', 'gold', 'golf', 'gong', 'good',
  'goose', 'gore', 'gown', 'grab', 'grade', 'graft', 'grain', 'gram', 'grand', 'grant',
  'grape', 'graph', 'grasp', 'grass', 'grate', 'grave', 'gravy', 'gray', 'graze', 'great',
  'greed', 'green', 'greet', 'grew', 'grid', 'grief', 'grill', 'grim', 'grin', 'grip',
  'grit', 'groan', 'groin', 'groom', 'gross', 'group', 'grout', 'grove', 'grow', 'growl',
  'grown', 'grub', 'gruff', 'grunt', 'guard', 'guess', 'guide', 'guild', 'gulf', 'gull',
  'gulp', 'gum', 'gummy', 'gun', 'gust', 'gut', 'guy', 'haiku', 'hail', 'hair',
  'half', 'hall', 'halo', 'halt', 'hand', 'hang', 'happy', 'hard', 'harm', 'harp',
  'hash', 'haste', 'hat', 'hatch', 'have', 'haven', 'hawk', 'hazel', 'hazy', 'head',
  'heal', 'heap', 'heat', 'heel', 'hedge', 'heft', 'helix', 'hello', 'help', 'hen',
  'herb', 'herd', 'hero', 'hex', 'hide', 'high', 'hike', 'hill', 'hilly', 'hilt',
  'hint', 'hippo', 'hip', 'hire', 'hiss', 'hit', 'hive', 'hoax', 'hobby', 'hog',
  'hole', 'holly', 'home', 'honey', 'hood', 'hoof', 'hook', 'hoop', 'hop', 'hope',
  'horde', 'horn', 'hose', 'host', 'hot', 'hotel', 'hound', 'hour', 'house', 'hover',
  'how', 'howl', 'hub', 'hug', 'huge', 'hull', 'hum', 'human', 'humid', 'hump',
  'hung', 'hunk', 'hunt', 'hurry', 'husk', 'hut', 'hyena', 'icing', 'icy', 'idea',
  'idle', 'igloo', 'imp', 'inch', 'index', 'inert', 'infer', 'ink', 'inlay', 'inner',
  'input', 'iris', 'iron', 'irony', 'isle', 'item', 'ivory', 'jab', 'jacks', 'jade',
  'jail', 'jam', 'jar', 'java', 'jazz', 'jeep', 'jelly', 'jerky', 'jest', 'jet',
  'jewel', 'jigsaw', 'job', 'jog', 'join', 'joint', 'joke', 'jolly', 'jolt', 'jot',
  'joust', 'joy', 'judge', 'juice', 'jumbo', 'jump', 'junk', 'jury', 'just', 'kale',
  'karma', 'kayak', 'keen', 'keep', 'keg', 'kelp', 'kept', 'ketch', 'key', 'khaki',
  'kick', 'kid', 'kilt', 'kin', 'kind', 'king', 'kiosk', 'kit', 'kite', 'kitty',
  'kiwi', 'knee', 'knelt', 'knew', 'knife', 'knob', 'knock', 'knoll', 'knot', 'know',
  'koala', 'label', 'labor', 'lace', 'lack', 'lad', 'ladle', 'lady', 'lair', 'lake',
  'lamb', 'lamp', 'land', 'lane', 'lank', 'lap', 'lapel', 'lard', 'large', 'lark',
  'lash', 'lasso', 'last', 'late', 'latte', 'laugh', 'lava', 'lawn', 'layer', 'leach',
  'lead', 'leaf', 'leak', 'lean', 'leap', 'learn', 'leash', 'least', 'leech', 'leek',
  'left', 'leg', 'lemon', 'lend', 'lens', 'lent', 'level', 'lever', 'lid', 'life',
  'lift', 'light', 'like', 'lilac', 'lily', 'limb', 'lime', 'limit', 'limo', 'limp',
  'line', 'linen', 'link', 'lint', 'lion', 'lip', 'list', 'litre', 'live', 'liver',
  'lizard', 'llama', 'load', 'loaf', 'loan', 'lobby', 'lobe', 'local', 'lock', 'lodge',
  'lofty', 'log', 'logic', 'loner', 'long', 'loop', 'loose', 'lord', 'lose', 'loss',
  'lotus', 'loud', 'lousy', 'love', 'lower', 'loyal', 'lucky', 'lull', 'lumen', 'lunar',
  'lunch', 'lung', 'lurch', 'lure', 'lush', 'lute', 'lying', 'lyric', 'macro', 'mad',
  'madam', 'made', 'mafia', 'magic', 'magma', 'maid', 'mail', 'main', 'major', 'make',
  'maker', 'male', 'mall', 'malt', 'mama', 'mane', 'mango', 'manor', 'many', 'map',
  'maple', 'march', 'mare', 'marsh', 'mash', 'mask', 'mass', 'mast', 'match', 'mate',
  'math', 'matte', 'mauve', 'mayo', 'maze', 'meant', 'meat', 'medal', 'media', 'medic',
  'melon', 'melt', 'memo', 'mend', 'menu', 'meow', 'mercy', 'merge', 'merit', 'merry',
  'mesh', 'metal', 'meter', 'metro', 'mica', 'micro', 'midst', 'might', 'milk', 'mill',
  'mimic', 'mind', 'mine', 'minor', 'mint', 'minus', 'mirth', 'miser', 'miss', 'mist',
  'mix', 'moan', 'moat', 'mocha', 'mock', 'modal', 'mode', 'model', 'modem', 'mold',
  'mole', 'molly', 'molt', 'mom', 'money', 'monk', 'mood', 'moody', 'moon', 'moose',
  'moral', 'more', 'morph', 'moss', 'most', 'moth', 'motor', 'motto', 'mound', 'mount',
  'mouse', 'mouth', 'move', 'movie', 'mower', 'much', 'mud', 'mug', 'muggy', 'mulch',
  'mule', 'mummy', 'munch', 'mural', 'muse', 'mushy', 'music', 'musk', 'must', 'mute',
  'mutt', 'myth', 'nacho', 'nag', 'name', 'nap', 'narrow', 'nasal', 'nasty', 'navy',
  'near', 'neat', 'neck', 'need', 'neon', 'nest', 'never', 'newt', 'next', 'nibs',
  'nice', 'niche', 'niece', 'night', 'nimbly', 'ninja', 'ninth', 'nip', 'noble', 'nod',
  'noise', 'noisy', 'nomad', 'none', 'noon', 'noose', 'normal', 'north', 'nose', 'note',
  'notch', 'nougat', 'novel', 'now', 'nudge', 'numb', 'nurse', 'nut', 'nylon', 'oak',
  'oasis', 'oat', 'oath', 'obey', 'oboe', 'ocean', 'octave', 'octopus', 'odd', 'oddly',
  'off', 'often', 'ogre', 'oil', 'oily', 'old', 'olive', 'omen', 'omit', 'onion',
  'only', 'onset', 'onto', 'opal', 'open', 'opera', 'opt', 'oral', 'orange', 'orb',
  'orca', 'order', 'organ', 'oryx', 'osprey', 'other', 'otter', 'ouch', 'ought', 'ounce',
  'oust', 'outer', 'oval', 'oven', 'over', 'owe', 'owl', 'own', 'oxen', 'pace',
  'pack', 'paddy', 'page', 'paid', 'pail', 'pain', 'paint', 'pair', 'palm', 'panda',
  'panel', 'panic', 'pansy', 'pant', 'papa', 'paper', 'parka', 'park', 'parley', 'parsley',
  'part', 'party', 'pass', 'paste', 'pasta', 'past', 'patch', 'path', 'patio', 'patty',
  'pause', 'pave', 'pawn', 'peace', 'peach', 'peak', 'pear', 'pearl', 'pen', 'penny',
  'perch', 'perk', 'perky', 'pesto', 'petal', 'pew', 'pewter', 'phase', 'photo', 'piano',
  'pick', 'piece', 'pier', 'pig', 'pike', 'pile', 'pill', 'pilot', 'pin', 'pinch',
  'pine', 'ping', 'pink', 'pint', 'pipe', 'piper', 'pirate', 'pita', 'pity', 'pixie',
  'pizza', 'place', 'plaid', 'plain', 'plait', 'plan', 'plank', 'plant', 'plate', 'play',
  'plaza', 'plead', 'pleat', 'pledge', 'plot', 'plow', 'pluck', 'plug', 'plum', 'plumb',
  'plump', 'plus', 'plush', 'pluto', 'pocket', 'pod', 'poem', 'poet', 'point', 'poise',
  'poker', 'polar', 'pole', 'polo', 'pomp', 'pond', 'pony', 'pool', 'poppy', 'porch',
  'port', 'posh', 'post', 'pouch', 'pound', 'pour', 'powder', 'power', 'praise', 'prank',
  'pray', 'press', 'prey', 'price', 'pride', 'prim', 'prime', 'print', 'prior', 'prism',
  'prize', 'proof', 'props', 'prose', 'proud', 'prove', 'prowl', 'prude', 'prune', 'pry',
  'pub', 'puck', 'puff', 'pulp', 'pulse', 'puma', 'punch', 'punk', 'puny', 'pupa',
  'pupil', 'puppy', 'puree', 'purge', 'purr', 'purse', 'push', 'putty', 'pygmy', 'quack',
  'quad', 'quail', 'quake', 'qualm', 'quark', 'quart', 'queen', 'quell', 'quest', 'quick',
  'quiet', 'quill', 'quilt', 'quirk', 'quote', 'rabid', 'race', 'rack', 'radar', 'radio',
  'radish', 'raft', 'rage', 'rail', 'rake', 'rally', 'ram', 'ranch', 'random', 'range',
  'rank', 'rant', 'raspy', 'rate', 'ratio', 'raven', 'razor', 'reach', 'read', 'real',
  'realm', 'reap', 'rear', 'rebel', 'reed', 'reef', 'reel', 'refer', 'regal', 'reign',
  'relax', 'relay', 'relic', 'rely', 'remit', 'renal', 'rerun', 'reset', 'rest', 'retry',
  'revel', 'revel', 'rhino', 'rib', 'rice', 'rich', 'rid', 'ride', 'ridge', 'rifle',
  'rig', 'right', 'rigid', 'rim', 'ring', 'rinse', 'riot', 'ripe', 'rise', 'risky',
  'rival', 'river', 'roach', 'road', 'roam', 'roar', 'roast', 'robe', 'robin', 'rock',
  'rod', 'rode', 'rodeo', 'rogue', 'roll', 'roman', 'roof', 'rook', 'room', 'roomy',
  'roost', 'root', 'rope', 'ropey', 'rose', 'rosy', 'rouge', 'rough', 'round', 'rouse',
  'rove', 'rover', 'rowdy', 'royal', 'rub', 'ruby', 'rudder', 'rude', 'ruff', 'rug',
  'rugby', 'ruin', 'rule', 'rum', 'rumor', 'run', 'rung', 'runt', 'rural', 'rush',
  'rusty', 'rye', 'sable', 'sack', 'sad', 'sadly', 'safe', 'saga', 'sage', 'sail',
  'saint', 'salad', 'salon', 'salsa', 'salt', 'salty', 'same', 'samba', 'sand', 'sandy',
  'sane', 'sap', 'sash', 'satin', 'sauce', 'sauna', 'savor', 'savvy', 'scale', 'scalp',
  'scan', 'scant', 'scar', 'scare', 'scarf', 'scary', 'scary', 'scene', 'scent', 'scoff',
  'scoop', 'scoot', 'score', 'scorn', 'scour', 'scout', 'scowl', 'scrap', 'scrub', 'scuba',
  'scuff', 'sea', 'seal', 'seam', 'seek', 'seem', 'seep', 'seethe', 'self', 'sell',
  'send', 'sense', 'sepia', 'serve', 'set', 'setup', 'seven', 'shack', 'shade', 'shaft',
  'shake', 'shaky', 'shall', 'shame', 'shape', 'share', 'shark', 'sharp', 'shawl', 'shed',
  'sheen', 'sheep', 'sheet', 'shelf', 'shell', 'shift', 'shin', 'shine', 'shiny', 'ship',
  'shirt', 'shoe', 'shop', 'shore', 'short', 'shout', 'shove', 'show', 'shown', 'shred',
  'shrew', 'shrub', 'shrug', 'shut', 'shy', 'sick', 'side', 'siege', 'sift', 'sigh',
  'sign', 'silk', 'silky', 'silly', 'silt', 'simple', 'since', 'sinew', 'sip', 'siren',
  'sit', 'site', 'six', 'sixth', 'sixty', 'size', 'sizzle', 'skate', 'sketch', 'ski',
  'skid', 'skill', 'skim', 'skin', 'skip', 'skirt', 'skit', 'skull', 'sky', 'slab',
  'slack', 'slain', 'slam', 'slang', 'slant', 'slap', 'slash', 'slate', 'sled', 'sleek',
  'sleep', 'sleet', 'slept', 'slice', 'slick', 'slid', 'slide', 'slim', 'slime', 'sling',
  'slip', 'slit', 'slob', 'slope', 'slot', 'slow', 'slug', 'slum', 'slung', 'slur',
  'slush', 'sly', 'smack', 'small', 'smart', 'smash', 'smear', 'smell', 'smelt', 'smile',
  'smirk', 'smith', 'smock', 'smog', 'smoke', 'smoky', 'snack', 'snag', 'snail', 'snake',
  'snap', 'snare', 'snarl', 'sneak', 'sneer', 'sniff', 'snip', 'snore', 'snort', 'snout',
  'snow', 'snowy', 'snub', 'snuck', 'snug', 'soak', 'soap', 'sober', 'soda', 'sofa',
  'soft', 'soggy', 'soil', 'solar', 'sold', 'sole', 'solid', 'solo', 'solve', 'some',
  'sonic', 'sooty', 'sore', 'sorry', 'sort', 'soul', 'soup', 'sour', 'south', 'sown',
  'soy', 'space', 'spade', 'spam', 'span', 'spare', 'spark', 'spasm', 'spat', 'spay',
  'spear', 'speck', 'sped', 'speed', 'spell', 'spend', 'spent', 'spice', 'spicy', 'spied',
  'spike', 'spill', 'spin', 'spine', 'spiny', 'spire', 'spite', 'splat', 'split', 'spoil',
  'spoke', 'spoof', 'spoon', 'sport', 'spot', 'spout', 'spray', 'spree', 'spry', 'spud',
  'spur', 'spurn', 'spurt', 'spy', 'squad', 'squat', 'stab', 'stack', 'stage', 'staid',
  'stain', 'stair', 'stake', 'stale', 'stalk', 'stall', 'stamp', 'stand', 'stank', 'star',
  'stare', 'start', 'state', 'stay', 'steak', 'steam', 'steel', 'steep', 'steer', 'stem',
  'step', 'stern', 'stew', 'stick', 'stiff', 'still', 'sting', 'stink', 'stir', 'stitch',
  'stock', 'stoic', 'stoke', 'stole', 'stomp', 'stone', 'stony', 'stood', 'stool', 'stoop',
  'stop', 'stork', 'storm', 'story', 'stout', 'stove', 'straw', 'stray', 'strip', 'strut',
  'study', 'stuff', 'stump', 'stung', 'stunt', 'style', 'sub', 'sue', 'suede', 'sugar',
  'suit', 'sulky', 'sum', 'sunny', 'super', 'surf', 'surge', 'sushi', 'swab', 'swam',
  'swamp', 'swan', 'swarm', 'swat', 'sway', 'swell', 'swept', 'swift', 'swim', 'swine',
  'swing', 'swipe', 'swirl', 'swiss', 'swoop', 'sword', 'swore', 'sworn', 'swum', 'sync',
];
