/**
 * Canonical Help Center - the unified in-app documentation browser shared by
 * every BigBlueBam app. Imported via a Vite alias in each SPA:
 *   '@bigbluebam/ui/help-center' -> '<root>/packages/ui/help-center.tsx'
 *
 * Two things an app wires in (see the suite-help-system skill):
 *
 *  1. <HelpTrigger app="<app>" /> in the top bar. Renders the "(?)" icon
 *     (tooltip "Help"). Clicking it opens a full-screen overlay with a TOC
 *     sidebar, client-side search, cross-references to sibling apps, and the
 *     rendered help.md content with deep-link anchors.
 *
 *  2. Right-click element help. HelpTrigger also installs a document-level
 *     contextmenu handler: right-clicking a *documented* control (a button,
 *     menu item, or any element carrying a label that appears in the app's
 *     help-index.json `labels` map) shows a "Help: <label>" item that opens
 *     the Help Center straight to the section documenting that control.
 *     Right-clicking anything undocumented leaves the native menu untouched.
 *
 * Data sources, both served statically by nginx under /docs/ (a compose bind
 * mount of ./docs/apps overlays the baked-in copy, so edits show without a
 * rebuild):
 *   /docs/apps/<app>/help.md          - the prose, rendered to HTML
 *   /docs/apps/<app>/help-index.json  - { title, toc, sections, labels, crossrefs }
 *                                       generated by scripts/help/build-help-index.mjs
 *
 * IMPORTANT: slugify() below MUST stay byte-for-byte identical to the
 * `slugify` in scripts/help/build-help-index.mjs. The index stores anchors
 * computed by that function; we re-slug the rendered headings with this one so
 * TOC/search/right-click deep-links land. If they drift, links silently miss.
 *
 * The consumer app provides the QueryClient via its own QueryClientProvider
 * (every app already does, for NotificationsBell).
 */

import { useCallback, useEffect, useMemo, useRef, useState, type FC, type ReactNode } from 'react';
import { useQuery } from '@tanstack/react-query';
import { HelpCircle, X, Search, BookOpen, ArrowLeft, Loader2, ExternalLink } from 'lucide-react';
import { markdownToHtml, sanitizeHtml } from '@bigbluebam/ui/markdown';

// ── Index shape (docs/apps/<app>/help-index.json) ────────────────────────────

interface TocEntry {
  anchor: string;
  title: string;
  level: number;
}
interface SectionEntry {
  anchor: string;
  title: string;
  text: string;
}
interface CrossRef {
  app: string;
  title: string;
}
interface HelpIndex {
  app: string;
  title: string;
  toc: TocEntry[];
  sections: SectionEntry[];
  labels: Record<string, string>;
  crossrefs: CrossRef[];
}

// ── Canonical heading slug (keep identical to build-help-index.mjs) ──────────

/** GitHub-style heading slug. MUST match scripts/help/build-help-index.mjs. */
export function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/`/g, '')
    .replace(/[^\w\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

// ── Global open bus ──────────────────────────────────────────────────────────
//
// Lets the right-click handler (and any external caller) drive the overlay
// without threading a context provider through every app. HelpTrigger
// subscribes on mount; openHelpCenter() fans out to whichever trigger is live.

type OpenListener = (app: string, anchor: string | null) => void;
const openListeners = new Set<OpenListener>();

/** Open the Help Center programmatically (app key, optional section anchor). */
export function openHelpCenter(app: string, anchor: string | null = null): void {
  for (const listener of openListeners) listener(app, anchor);
}

// ── Data hooks ───────────────────────────────────────────────────────────────

function useHelpIndex(app: string) {
  return useQuery<HelpIndex>({
    queryKey: ['help-center', 'index', app],
    queryFn: async () => {
      const res = await fetch(`/docs/apps/${app}/help-index.json`, { credentials: 'include' });
      if (!res.ok) throw new Error(`help-index ${res.status}`);
      return res.json();
    },
    staleTime: 60 * 60 * 1000,
    retry: 1,
  });
}

function useHelpMarkdown(app: string) {
  return useQuery<string>({
    queryKey: ['help-center', 'md', app],
    queryFn: async () => {
      const res = await fetch(`/docs/apps/${app}/help.md`, { credentials: 'include' });
      if (!res.ok) throw new Error(`help.md ${res.status}`);
      return res.text();
    },
    staleTime: 60 * 60 * 1000,
    retry: 1,
  });
}

// ── Right-click label resolution ─────────────────────────────────────────────

/** Match a candidate string against the index labels (exact, then case-fold). */
function matchLabel(
  candidate: string,
  labels: Record<string, string>,
): { label: string; anchor: string } | null {
  const c = candidate.replace(/\s+/g, ' ').trim();
  if (!c) return null;
  const exact = labels[c];
  if (exact) return { label: c, anchor: exact };
  const cl = c.toLowerCase();
  for (const [k, v] of Object.entries(labels)) {
    if (k.toLowerCase() === cl) return { label: k, anchor: v };
  }
  return null;
}

/**
 * Walk up from the right-clicked element looking for a documented control.
 * Candidate strings, in priority order: an explicit data-help-label, then
 * aria-label / title, then the trimmed textContent of compact interactive
 * elements (so we never match a giant paragraph). Returns the first label
 * that exists in the index, or null (leave the native context menu alone).
 */
function resolveLabel(
  start: Element | null,
  labels: Record<string, string>,
): { label: string; anchor: string } | null {
  let el: Element | null = start;
  for (let depth = 0; el && depth < 6; depth++, el = el.parentElement) {
    const explicit = el.getAttribute?.('data-help-label');
    if (explicit) {
      const hit = matchLabel(explicit, labels);
      if (hit) return hit;
    }
    const aria = el.getAttribute?.('aria-label');
    if (aria) {
      const hit = matchLabel(aria, labels);
      if (hit) return hit;
    }
    const title = el.getAttribute?.('title');
    if (title) {
      const hit = matchLabel(title, labels);
      if (hit) return hit;
    }
    const tag = el.tagName?.toLowerCase();
    const role = el.getAttribute?.('role');
    const interactive =
      tag === 'button' ||
      tag === 'a' ||
      tag === 'label' ||
      tag === 'summary' ||
      role === 'button' ||
      role === 'menuitem' ||
      role === 'tab' ||
      role === 'option';
    if (interactive) {
      const txt = (el.textContent || '').replace(/\s+/g, ' ').trim();
      if (txt && txt.length <= 60) {
        const hit = matchLabel(txt, labels);
        if (hit) return hit;
      }
    }
  }
  return null;
}

// ── Search helpers ───────────────────────────────────────────────────────────

function makeSnippet(text: string, idx: number, len: number): string {
  const start = Math.max(0, idx - 50);
  const end = Math.min(text.length, idx + len + 80);
  return (start > 0 ? '…' : '') + text.slice(start, end).trim() + (end < text.length ? '…' : '');
}

function Highlight({ text, term }: { text: string; term: string }): ReactNode {
  if (!term) return text;
  const i = text.toLowerCase().indexOf(term.toLowerCase());
  if (i < 0) return text;
  return (
    <>
      {text.slice(0, i)}
      <mark className="rounded bg-amber-200 px-0.5 text-inherit dark:bg-amber-500/40">
        {text.slice(i, i + term.length)}
      </mark>
      {text.slice(i + term.length)}
    </>
  );
}

// ── The overlay ──────────────────────────────────────────────────────────────

interface OverlayProps {
  app: string;
  anchor: string | null;
  /** The app the trigger belongs to, so "back" can return to it from a crossref. */
  homeApp: string;
  onAppChange: (app: string) => void;
  onAnchorChange: (anchor: string | null) => void;
  onClose: () => void;
}

function HelpCenterOverlay({
  app,
  anchor,
  homeApp,
  onAppChange,
  onAnchorChange,
  onClose,
}: OverlayProps) {
  const { data: index, isLoading: idxLoading } = useHelpIndex(app);
  const { data: markdown, isLoading: mdLoading, error } = useHelpMarkdown(app);
  const [query, setQuery] = useState('');
  const contentRef = useRef<HTMLDivElement>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  const html = useMemo(
    () => (markdown ? sanitizeHtml(markdownToHtml(markdown)) : ''),
    [markdown],
  );

  // After render: re-slug headings to match index anchors exactly, and rewrite
  // relative image/link URLs (help.md uses paths like `screenshots/light/x.png`
  // which would otherwise resolve against the SPA route, 404ing) to /docs/apps/<app>/.
  useEffect(() => {
    const root = contentRef.current;
    if (!root) return;
    root.querySelectorAll('h1,h2,h3,h4,h5,h6').forEach((h) => {
      const id = slugify(h.textContent || '');
      if (id) h.id = id;
    });
    const base = `/docs/apps/${app}/`;
    const isAbsolute = (u: string) => /^(https?:|\/|#|data:|mailto:)/.test(u);
    root.querySelectorAll('img').forEach((img) => {
      const src = img.getAttribute('src') || '';
      if (src && !isAbsolute(src)) img.setAttribute('src', base + src);
      img.setAttribute('loading', 'lazy');
    });
    root.querySelectorAll('a').forEach((a) => {
      const href = a.getAttribute('href') || '';
      if (href && !isAbsolute(href)) a.setAttribute('href', base + href);
    });
  }, [html, app]);

  // Scroll to the active anchor when it changes or the content loads.
  useEffect(() => {
    if (!anchor || !html) return;
    const t = setTimeout(() => {
      const el = contentRef.current?.querySelector(`#${CSS.escape(anchor)}`);
      if (el) el.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }, 80);
    return () => clearTimeout(t);
  }, [anchor, html]);

  // No anchor (fresh app / cleared search): pin the content scroll to the top.
  useEffect(() => {
    if (anchor) return;
    scrollRef.current?.scrollTo({ top: 0 });
  }, [app, anchor]);

  // Escape closes; lock the page behind the overlay while it's open.
  useEffect(() => {
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('keydown', onKey);
    const prevOverflow = document.body.style.overflow;
    document.body.style.overflow = 'hidden';
    return () => {
      document.removeEventListener('keydown', onKey);
      document.body.style.overflow = prevOverflow;
    };
  }, [onClose]);

  // In-doc anchor links ([text](#anchor)) scroll within the pane.
  const onContentClick = (e: React.MouseEvent) => {
    const a = (e.target as HTMLElement).closest('a');
    if (!a) return;
    const href = a.getAttribute('href') || '';
    if (href.startsWith('#')) {
      e.preventDefault();
      onAnchorChange(href.slice(1));
    }
  };

  const q = query.trim();
  const results = useMemo(() => {
    const needle = q.toLowerCase();
    if (!needle || !index) return [];
    return index.sections
      .map((s) => {
        const inTitle = s.title.toLowerCase().includes(needle);
        const ti = s.text.toLowerCase().indexOf(needle);
        if (!inTitle && ti < 0) return null;
        const snippet = ti >= 0 ? makeSnippet(s.text, ti, needle.length) : s.text.slice(0, 140);
        return { anchor: s.anchor, title: s.title, snippet, score: inTitle ? 0 : 1 };
      })
      .filter((r): r is { anchor: string; title: string; snippet: string; score: number } => r !== null)
      .sort((a, b) => a.score - b.score)
      .slice(0, 30);
  }, [q, index]);

  const title = index?.title ?? app;
  const isCrossApp = app !== homeApp;

  return (
    // Backdrop. Clicking it (but not the panel) closes.
    <div
      className="fixed inset-0 z-[200] flex bg-black/40 backdrop-blur-sm"
      role="presentation"
      onMouseDown={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-label={`${title} help`}
        className="m-auto flex h-[90vh] w-[min(1100px,95vw)] flex-col overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-2xl dark:border-zinc-800 dark:bg-zinc-950"
      >
        {/* Header: title, search, close */}
        <div className="flex items-center gap-3 border-b border-zinc-200 px-5 py-3 dark:border-zinc-800">
          {isCrossApp && (
            <button
              type="button"
              onClick={() => {
                onAppChange(homeApp);
                onAnchorChange(null);
                setQuery('');
              }}
              className="rounded-lg p-1.5 text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-700 dark:hover:bg-zinc-800 dark:hover:text-zinc-300"
              title="Back"
              aria-label="Back to this app's help"
            >
              <ArrowLeft className="h-4.5 w-4.5" />
            </button>
          )}
          <BookOpen className="h-5 w-5 text-primary-600 dark:text-primary-400" aria-hidden="true" />
          <h2 className="text-base font-semibold text-zinc-900 dark:text-zinc-100">{title} Help</h2>
          <div className="flex-1" />
          <div className="relative w-72 max-w-[40vw]">
            <Search
              className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-zinc-400"
              aria-hidden="true"
            />
            <input
              type="search"
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              placeholder={`Search ${title} help...`}
              aria-label={`Search ${title} help`}
              className="w-full rounded-lg border border-zinc-200 bg-zinc-50 py-1.5 pl-9 pr-3 text-sm focus:outline-none focus:ring-2 focus:ring-primary-500 dark:border-zinc-700 dark:bg-zinc-800 dark:text-zinc-100"
            />
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-1.5 text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-700 dark:hover:bg-zinc-800 dark:hover:text-zinc-300"
            title="Close"
            aria-label="Close help"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Body: sidebar + content */}
        <div className="flex flex-1 overflow-hidden">
          <nav
            aria-label="Help contents"
            className="hidden w-64 shrink-0 flex-col overflow-y-auto border-r border-zinc-200 p-3 md:flex dark:border-zinc-800"
          >
            {q ? (
              <div>
                <p className="px-2 pb-2 text-xs font-medium uppercase tracking-wide text-zinc-400">
                  {results.length} result{results.length === 1 ? '' : 's'}
                </p>
                {results.length === 0 ? (
                  <p className="px-2 text-sm text-zinc-400">No matches.</p>
                ) : (
                  <ul className="space-y-1">
                    {results.map((r) => (
                      <li key={r.anchor}>
                        <button
                          type="button"
                          onClick={() => onAnchorChange(r.anchor)}
                          className="w-full rounded-md px-2 py-1.5 text-left transition-colors hover:bg-zinc-100 dark:hover:bg-zinc-800"
                        >
                          <span className="block text-sm font-medium text-zinc-800 dark:text-zinc-200">
                            <Highlight text={r.title} term={q} />
                          </span>
                          <span className="mt-0.5 block text-xs leading-snug text-zinc-500 dark:text-zinc-400">
                            <Highlight text={r.snippet} term={q} />
                          </span>
                        </button>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            ) : (
              <>
                <ul className="space-y-0.5">
                  {(index?.toc ?? []).map((t) => (
                    <li key={t.anchor}>
                      <button
                        type="button"
                        onClick={() => onAnchorChange(t.anchor)}
                        style={{ paddingLeft: `${(Math.max(2, t.level) - 2) * 12 + 8}px` }}
                        className={`w-full rounded-md py-1 pr-2 text-left text-sm transition-colors hover:bg-zinc-100 dark:hover:bg-zinc-800 ${
                          anchor === t.anchor
                            ? 'bg-primary-50 font-medium text-primary-700 dark:bg-primary-500/10 dark:text-primary-300'
                            : t.level <= 2
                              ? 'font-medium text-zinc-800 dark:text-zinc-200'
                              : 'text-zinc-600 dark:text-zinc-400'
                        }`}
                      >
                        {t.title}
                      </button>
                    </li>
                  ))}
                </ul>

                {index?.crossrefs && index.crossrefs.length > 0 && (
                  <div className="mt-4 border-t border-zinc-200 pt-3 dark:border-zinc-800">
                    <p className="px-2 pb-1.5 text-xs font-medium uppercase tracking-wide text-zinc-400">
                      Related apps
                    </p>
                    <ul className="space-y-0.5">
                      {index.crossrefs.map((x) => (
                        <li key={x.app}>
                          <button
                            type="button"
                            onClick={() => {
                              onAppChange(x.app);
                              onAnchorChange(null);
                              setQuery('');
                            }}
                            className="flex w-full items-center gap-1.5 rounded-md px-2 py-1 text-left text-sm text-zinc-600 transition-colors hover:bg-zinc-100 dark:text-zinc-400 dark:hover:bg-zinc-800"
                          >
                            <ExternalLink className="h-3.5 w-3.5 shrink-0 text-zinc-400" />
                            {x.title}
                          </button>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </>
            )}
          </nav>

          <div ref={scrollRef} className="flex-1 overflow-y-auto">
            <div className="mx-auto max-w-3xl px-6 py-6">
              {(idxLoading || mdLoading) && !html && (
                <div className="flex items-center justify-center py-20 text-zinc-500">
                  <Loader2 className="h-5 w-5 animate-spin text-primary-500" />
                  <span className="ml-3">Loading help…</span>
                </div>
              )}
              {error && !html && (
                <div className="py-20 text-center">
                  <BookOpen className="mx-auto mb-4 h-10 w-10 text-zinc-300 dark:text-zinc-700" />
                  <p className="text-zinc-500 dark:text-zinc-400">
                    Help content is not available for this app yet.
                  </p>
                </div>
              )}
              {html && (
                <div
                  ref={contentRef}
                  onClick={onContentClick}
                  className="help-center-content prose prose-zinc max-w-none dark:prose-invert"
                  // Content is sanitized by sanitizeHtml(markdownToHtml(...)).
                  dangerouslySetInnerHTML={{ __html: html }}
                />
              )}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Public: HelpCenter (controlled overlay) ──────────────────────────────────

export interface HelpCenterProps {
  app: string;
  open: boolean;
  anchor?: string | null;
  onClose: () => void;
}

/**
 * Controlled overlay, for apps that want to own the open state (e.g. open Help
 * from a custom menu). Most apps just use <HelpTrigger/>, which renders this.
 */
export const HelpCenter: FC<HelpCenterProps> = ({ app, open, anchor = null, onClose }) => {
  const [activeApp, setActiveApp] = useState(app);
  const [activeAnchor, setActiveAnchor] = useState<string | null>(anchor);
  useEffect(() => {
    if (open) {
      setActiveApp(app);
      setActiveAnchor(anchor);
    }
  }, [open, app, anchor]);
  if (!open) return null;
  return (
    <HelpCenterOverlay
      app={activeApp}
      anchor={activeAnchor}
      homeApp={app}
      onAppChange={setActiveApp}
      onAnchorChange={setActiveAnchor}
      onClose={onClose}
    />
  );
};

// ── Public: HelpTrigger (the "(?)" icon + right-click help) ───────────────────

export interface HelpTriggerProps {
  /** App key, e.g. "bam" or "blast". Selects which /docs/apps/<app>/ to load. */
  app: string;
  className?: string;
  /** Right-click "Help: <element>" augmentation. Default on. */
  contextHelp?: boolean;
}

/**
 * The header "(?)" button. Renders the overlay on demand, subscribes to the
 * global open bus, and (unless disabled) installs the right-click element-help
 * handler for documented controls.
 */
export const HelpTrigger: FC<HelpTriggerProps> = ({ app, className, contextHelp = true }) => {
  const [open, setOpen] = useState(false);
  const [activeApp, setActiveApp] = useState(app);
  const [anchor, setAnchor] = useState<string | null>(null);
  const [ctxMenu, setCtxMenu] = useState<{ x: number; y: number; label: string; anchor: string } | null>(
    null,
  );

  // Load this app's index eagerly so right-click resolution works before the
  // overlay is ever opened. Held in a ref for the (non-React) event handler.
  const { data: index } = useHelpIndex(app);
  const indexRef = useRef<HelpIndex | undefined>(undefined);
  indexRef.current = index;

  const openTo = useCallback((toApp: string, toAnchor: string | null) => {
    setActiveApp(toApp);
    setAnchor(toAnchor);
    setOpen(true);
  }, []);

  // Global open bus (right-click + external openHelpCenter() callers).
  useEffect(() => {
    const listener: OpenListener = (toApp, toAnchor) => openTo(toApp || app, toAnchor);
    openListeners.add(listener);
    return () => {
      openListeners.delete(listener);
    };
  }, [app, openTo]);

  // Right-click element help: offer "Help: <label>" only on documented controls.
  useEffect(() => {
    if (!contextHelp) return;
    const onContext = (e: MouseEvent) => {
      const idx = indexRef.current;
      if (!idx) return;
      const hit = resolveLabel(e.target as Element | null, idx.labels);
      if (!hit) return; // undocumented - leave the native menu alone
      e.preventDefault();
      setCtxMenu({ x: e.clientX, y: e.clientY, label: hit.label, anchor: hit.anchor });
    };
    document.addEventListener('contextmenu', onContext);
    return () => document.removeEventListener('contextmenu', onContext);
  }, [contextHelp]);

  // Dismiss the floating help menu on any click / scroll / Escape.
  useEffect(() => {
    if (!ctxMenu) return;
    const dismiss = () => setCtxMenu(null);
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setCtxMenu(null);
    };
    document.addEventListener('click', dismiss);
    document.addEventListener('scroll', dismiss, true);
    document.addEventListener('keydown', onKey);
    return () => {
      document.removeEventListener('click', dismiss);
      document.removeEventListener('scroll', dismiss, true);
      document.removeEventListener('keydown', onKey);
    };
  }, [ctxMenu]);

  return (
    <>
      <button
        type="button"
        onClick={() => openTo(app, null)}
        className={
          className ??
          'rounded-lg p-2 text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-700 dark:hover:bg-zinc-800 dark:hover:text-zinc-300'
        }
        title="Help"
        aria-label="Help"
        aria-haspopup="dialog"
      >
        <HelpCircle className="h-4.5 w-4.5" aria-hidden="true" />
      </button>

      {ctxMenu && (
        <div
          className="fixed z-[210] overflow-hidden rounded-lg border border-zinc-200 bg-white py-1 shadow-xl dark:border-zinc-700 dark:bg-zinc-800"
          style={{ top: Math.min(ctxMenu.y, window.innerHeight - 48), left: Math.min(ctxMenu.x, window.innerWidth - 240) }}
          role="menu"
        >
          <button
            type="button"
            role="menuitem"
            onClick={() => {
              openTo(app, ctxMenu.anchor);
              setCtxMenu(null);
            }}
            className="flex w-full items-center gap-2 px-3 py-1.5 text-left text-sm text-zinc-700 transition-colors hover:bg-primary-50 hover:text-primary-700 dark:text-zinc-200 dark:hover:bg-zinc-700"
          >
            <HelpCircle className="h-3.5 w-3.5 shrink-0 text-zinc-400" />
            <span className="truncate">
              Help: <span className="font-medium">{ctxMenu.label}</span>
            </span>
          </button>
        </div>
      )}

      {open && (
        <HelpCenterOverlay
          app={activeApp}
          anchor={anchor}
          homeApp={app}
          onAppChange={setActiveApp}
          onAnchorChange={setAnchor}
          onClose={() => setOpen(false)}
        />
      )}
    </>
  );
};
